name: Format Python Code with Black

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  format:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4  # Replace with your desired Python version.

      - name: Install Black
        run: pip install black

      - name: Find and Format Python Files
        run: |
          find . -name "*.py" -exec black {} \;
        shell: bash

      - name: Commit and Push Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Format Python code with Black"
          git push
        working-directory: ${{ github.workspace }}
