name: Generic Workflow

on:
  push:
    branches:
      - '*'
    tags:
      - '*' 
    paths:
      - '**.py'

jobs:
  pylint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10.4"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Use v2 for better compatibility

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2  # Use v2 for better compatibility
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
         fetch-depth: 0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: List Changed Python Files
        id: list_changed_files
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '**.py')
          echo "::set-output name=changed_files::${changed_files}"
      - name: Run Pylint and Store Score
        id: run_pylint
        run: |
          changed_files="${{ steps.list_changed_files.outputs.changed_files }}"
          threshold=0.8  # Set your desired threshold here
          pylint_fail=false
          main_report_file="pylint_report.txt"
          scores=""
          if [ -n "$changed_files" ]; then
            
            for file in $changed_files; do
              
              pylint_score=$(pylint "$file" | grep 'Your code has been rated at' | awk '{print $7}' || echo "0")
              echo "Pylint score for $file: $pylint_score"
              if (( $(echo "$pylint_score >= $threshold" | bc -l) )); then
                 echo "Pylint score meets or exceeds the threshold for $file. Committing and pushing to GitHub."
              else
                echo "Pylint score for $file is below the threshold. Skipping."
                pylint_fail=true
              
              # Append the score to the scores string
              scores="$scores\n$file: $pylint_score"
          done   
            if [ "$pylint_fail" = true ]; then
              echo "At least one file has a Pylint score below the threshold. Aborting the workflow."
            else
                 echo "All files meet or exceed the threshold. Committing and pushing to GitHub."
              
                 token=${{ secrets.ATF }}
                 git config user.name "GitHub Actions"
                 git config user.email "actions@github.com"
                 branch_name="${{ github.ref }}"
                 branch_name="${branch_name#refs/heads/}"
                 git add "$file"
                 git push --force origin $branch_name 
                 echo "Committed and pushed to GitHub."
            fi 

          else
            echo "No Python files changed."
          fi  
          echo "## EDR Linter and Formatter" >> pylint_report.txt
          echo "Branch: ${{ github.ref }}" >> pylint_report.txt
          echo "==========" >> pylint_report.txt
          echo "Commit chain:" >> pylint_report.txt
          git log -n 3 --pretty=format:"- %h %s" >> pylint_report.txt
          echo "" >> pylint_report.txt
          echo "==========" >> pylint_report.txt
          echo "Files changed in latest commit:" >> pylint_report.txt
          echo "$file" >> pylint_report.txt
          echo "==========" >> pylint_report.txt
          echo "Author: ${{ github.actor }}" >> pylint_report.txt
          echo "Reviewer: ${{ github.actor }}" >> pylint_report.txt
          echo "Code Quality:" >> pylint_report.txt
          {
             echo "    Benchmark: 8"
             echo "    Code_Score: $pylint_score"
             if [ "$pylint_fail" = true ]; then
                  echo "    Check Status: Fail"
             fi
          } >> pylint_report.txt

          
          
          
          
          echo "Markdown report created."
          echo "::set-output name=markdown_report::pylint_report.txt"
      - name: Upload Markdown Report
        uses: actions/upload-artifact@v2
        with:
          name: pylint-report
          path: pylint_report.txt
