name: Lint and Commit Python Code

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  lint_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  # Change to your desired Python version

      - name: Install pylint
        run: pip install pylint
      - name: Install  autopep8
        run: pip install autopep8

      - name: Lint Python Code
        id: lint
        run: |
          python lint.py
        continue-on-error: true  # Continue even if linting fails to evaluate the exit code

      - name: Commit Changes
        if: steps.lint.outputs.return-code == '0'  # Only if linting passed
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "agarwalpankaj20000@gmail.com"
          git add .
          git commit -m "Linting passed. Committing changes."
          git push origin main

      - name: Create and Attach Report
        if: steps.lint.outputs.return-code == '0'  # Only if linting passed
        run: |
          echo "# Linting Report" > linting_report.md
          echo "Linting passed with a score of ${{ steps.lint.outputs.return-code }}." >> linting_report.md
          git add linting_report.md
          git commit -m "Add linting report"
          git push origin main
