name: Pylint Workflow

on:
  push:
    branches:
      - devops_code  # Change this to your main branch name if it's different
    paths:
      - '**.py'

jobs:
  pylint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10.4"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Use v2 for better compatibility

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2  # Use v2 for better compatibility
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
         fetch-depth: 0


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: List Changed Python Files
        id: list_changed_files
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '**.py')
          echo "::set-output name=changed_files::${changed_files}"

      - name: Run Pylint and Store Score
        id: run_pylint
        run: |
             changed_files="${{ steps.list_changed_files.outputs.changed_files }}"
             if [ -n "$changed_files" ]; then
    
                pylint_scores=()
             for file in $changed_files; do
                score=$(pylint "$file" | grep 'Your code has been rated at' | awk '{print $7}' || echo "0")
                pylint_scores+=("$score")
             done

   
             total_score=0
             for score in "${pylint_scores[@]}"; do
                 total_score=$(echo "$total_score + $score" | bc)
             done
             average_score=$(echo "scale=2; $total_score / ${#pylint_scores[@]}" | bc)

             echo "Pylint Scores: ${pylint_scores[@]}"
             echo "Average Pylint Score: $average_score"
             echo "::set-output name=score_float::${average_score}"
             else
                echo "No Python files changed."
             fi
