name: Pylint Workflow

on:
  push:
    branches:
      - main  # Change this to your main branch name if it's different

jobs:
  pylint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9  # Specify your Python version here

    - name: Install Dependencies
      run: pip install pylint PyGithub markdown

    - name: Run Pylint
      run: |
        pylint factorial.py > pylint_report.txt
        pylint_score=$(grep 'Your code has been rated at' pylint_report.txt | awk '{print $7}')
        echo "Pylint Score: $pylint_score"
        if (( $(bc <<< "$pylint_score < 6") )); then
          echo "Pylint score is less than 6. Workflow failed."
          exit 1
        fi
        echo "::set-output name=score_float::${pylint_score}"

    - name: Commit and Push if Pylint Score > 6
      if: ${{ success() }}
      run: |
        token=${{ secrets.GITHUB_TOKEN }}
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git checkout -b pylint-report
        git add pylint_report.txt
        git commit -m "Pylint report update"
        git push --force origin pylint-report
        echo "Committed and pushed to GitHub."

    - name: Create Markdown Report
      if: ${{ success() }}
      run: |
        echo "## Pylint Score: $pylint_score" > pylint_report.md
        cat pylint_report.txt >> pylint_report.md
        echo "Markdown report created."
        echo "::set-output name=markdown_report::pylint_report.md"

    - name: Upload Markdown Report
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: pylint-report
        path: pylint_report.md
