name: Pylint Workflow

on:
  push:
    branches:
      - devops_code  # Change this to your main branch name if it's different
    paths:
      - '**.py'

jobs:
  pylint:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.10.4"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Use v2 for better compatibility

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2  # Use v2 for better compatibility
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: List Changed Python Files
        id: list_changed_files
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- '**.py')
          echo "::set-output name=changed_files::${changed_files}"

      - name: Run Pylint and Store Score
        id: run_pylint
        run: |
          changed_files="${{ steps.list_changed_files.outputs.changed_files }}"
          if [ -n "$changed_files" ]; then
            pylint $changed_files > pylint_report.txt || exit 0
            pylint_score=$(grep 'Your code has been rated at' pylint_report.txt | awk '{print $7}' || echo "0")
            echo "Pylint Score: $pylint_score"
            echo "::set-output name=score_float::${pylint_score}"
          else
            echo "No Python files changed."
          fi

      - name: Display Pylint Score
        run: |
          echo "Pylint Score: ${{ steps.run_pylint.outputs.score_float }}"

