name: Pylint Job

on:
  push:
    branches:
      - main

jobs:
  pylint:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4


      - name: Determine changed Python files
        id: changed_files
        run: |
          changed_files=($(git diff --name-only origin/main...HEAD | grep '\.py$'))
          echo "::set-output name=changed_files::${changed_files[@]}"

      - name: Run Pylint and Check Score
        id: pylint_check
        run: |
          changed_files=(${{ steps.changed_files.outputs.changed_files }})
          pylint_fail=false

          for file in "${changed_files[@]}"; do
            pylint_report="${file%.py}_pylint_report.txt"
            pylint "$file" > "$pylint_report" || true
            pylint_score=$(grep -oP '(?<=Your code has been rated at ).*(?=/10)' "$pylint_report")

            if (( $(echo "$pylint_score < 6" | bc -l) )); then
              echo "Pylint score is less than 6 for $file. Aborting."
              pylint_fail=true
            fi
          done

          if [ "$pylint_fail" = true ]; then
            echo "::set-output name=fail::true"
            exit 1
          fi

      - name: Commit, Push, and Attach Report
        if: steps.pylint_check.outputs.fail != 'true'
        run: |
          changed_files=(${{ steps.changed_files.outputs.changed_files }})

          for file in "${changed_files[@]}"; do
            pylint_report="${file%.py}_pylint_report.txt"
            git config user.name "GitHub Actions"
            git config user.email "actions@github.com"
            git add "$file" "$pylint_report"
            git commit -m "Pylint report update for $file"
          done

          git push origin HEAD:main

      - name: Upload Pylint Reports
        if: steps.pylint_check.outputs.fail != 'true'
        uses: actions/upload-artifact@v2
        with:
          name: pylint-reports
          path: pylint_report.md
